src/Entity/FilamentMaterial.php
<?php

namespace App\Entity;

use App\Repository\FilamentMaterialRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilamentMaterialRepository::class)]
class FilamentMaterial
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $material_name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $material_description = null;

    /**
     * @var Collection<int, Filament>
     */
    #[ORM\OneToMany(targetEntity: Filament::class, mappedBy: 'material')]
    private Collection $filaments;

    public function __construct()
    {
        $this->filaments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMaterialName(): ?string
    {
        return $this->material_name;
    }

    public function setMaterialName(string $material_name): static
    {
        $this->material_name = $material_name;

        return $this;
    }

    public function getMaterialDescription(): ?string
    {
        return $this->material_description;
    }

    public function setMaterialDescription(?string $material_description): static
    {
        $this->material_description = $material_description;

        return $this;
    }

    /**
     * @return Collection<int, Filament>
     */
    public function getFilaments(): Collection
    {
        return $this->filaments;
    }

    public function addFilament(Filament $filament): static
    {
        if (!$this->filaments->contains($filament)) {
            $this->filaments->add($filament);
            $filament->setMaterial($this);
        }

        return $this;
    }

    public function removeFilament(Filament $filament): static
    {
        if ($this->filaments->removeElement($filament)) {
            // set the owning side to null (unless already changed)
            if ($filament->getMaterial() === $this) {
                $filament->setMaterial(null);
            }
        }

        return $this;
    }
}

src/Form/FilamentMaterialType.php
<?php

namespace App\Form;

use App\Entity\FilamentMaterial;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilamentMaterialType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('material_name')
            ->add('material_description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FilamentMaterial::class,
        ]);
    }
}

src/Controller/FilamentMaterialController.php
<?php

namespace App\Controller;

use App\Entity\FilamentMaterial;
use App\Form\FilamentMaterialType;
use App\Repository\FilamentMaterialRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin//filament/material')]
final class FilamentMaterialController extends AbstractController
{
    #[Route(name: 'app_filament_material_index', methods: ['GET'])]
    public function index(FilamentMaterialRepository $filamentMaterialRepository): Response
    {
        return $this->render('filament_material/index.html.twig', [
            'filament_materials' => $filamentMaterialRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_filament_material_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $filamentMaterial = new FilamentMaterial();
        $form = $this->createForm(FilamentMaterialType::class, $filamentMaterial);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($filamentMaterial);
            $entityManager->flush();

            return $this->redirectToRoute('app_filament_material_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('filament_material/new.html.twig', [
            'filament_material' => $filamentMaterial,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_filament_material_show', methods: ['GET'])]
    public function show(FilamentMaterial $filamentMaterial): Response
    {
        return $this->render('filament_material/show.html.twig', [
            'filament_material' => $filamentMaterial,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_filament_material_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FilamentMaterial $filamentMaterial, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FilamentMaterialType::class, $filamentMaterial);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_filament_material_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('filament_material/edit.html.twig', [
            'filament_material' => $filamentMaterial,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_filament_material_delete', methods: ['POST'])]
    public function delete(Request $request, FilamentMaterial $filamentMaterial, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$filamentMaterial->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($filamentMaterial);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_filament_material_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/filament_material/_delete_form.html.twig
<form method="post" action="{{ path('app_filament_material_delete', {'id': filament_material.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ filament_material.id) }}">
    <button class="btn">Delete</button>
</form>

templates/filament_material/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/filament_material/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FilamentMaterial{% endblock %}

{% block body %}
    <h1>Edit FilamentMaterial</h1>

    {{ include('filament_material/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_filament_material_index') }}">back to list</a>

    {{ include('filament_material/_delete_form.html.twig') }}
{% endblock %}

templates/filament_material/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FilamentMaterial index{% endblock %}

{% block body %}
    <h1>FilamentMaterial index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Material_name</th>
                <th>Material_description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for filament_material in filament_materials %}
            <tr>
                <td>{{ filament_material.id }}</td>
                <td>{{ filament_material.materialName }}</td>
                <td>{{ filament_material.materialDescription }}</td>
                <td>
                    <a href="{{ path('app_filament_material_show', {'id': filament_material.id}) }}">show</a>
                    <a href="{{ path('app_filament_material_edit', {'id': filament_material.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_filament_material_new') }}">Create new</a>
{% endblock %}

templates/filament_material/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FilamentMaterial{% endblock %}

{% block body %}
    <h1>Create new FilamentMaterial</h1>

    {{ include('filament_material/_form.html.twig') }}

    <a href="{{ path('app_filament_material_index') }}">back to list</a>
{% endblock %}

templates/filament_material/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FilamentMaterial{% endblock %}

{% block body %}
    <h1>FilamentMaterial</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ filament_material.id }}</td>
            </tr>
            <tr>
                <th>Material_name</th>
                <td>{{ filament_material.materialName }}</td>
            </tr>
            <tr>
                <th>Material_description</th>
                <td>{{ filament_material.materialDescription }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_filament_material_index') }}">back to list</a>

    <a href="{{ path('app_filament_material_edit', {'id': filament_material.id}) }}">edit</a>

    {{ include('filament_material/_delete_form.html.twig') }}
{% endblock %}